services: 
  dagros:
    container_name: dagros
    build: .
    network_mode: "host"
    volumes:
      - \\wsl$\Ubuntu-20.04\tmp\.X11-unix:/tmp/.X11-unix
      - \\wsl$\Ubuntu-20.04\usr\lib\wsl:/usr/lib/wsl
      - \\wsl$\Ubuntu-20.04\mnt\wslg:/mnt/wslg
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/run/user/1000/
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer